spring.application.name=pricewatch
spring.jpa.hibernate.ddl-auto=update
spring.profiles.include=secrets
#server.tomcat.accesslog.enabled=true
#server.tomcat.accesslog.directory=logs
#server.tomcat.accesslog.pattern=%t "%r" %s
logging.level.org.springframework.web=DEBUG