spring.application.name=pricewatch
spring.jpa.hibernate.ddl-auto=update
spring.profiles.include=secrets
#server.tomcat.accesslog.enabled=true
#server.tomcat.accesslog.directory=logs
#server.tomcat.accesslog.pattern=%t "%r" %s
#logging.level.org.springframework.web=DEBUG
logging.level.com.tameem.pricewatch=DEBUG
spring.jpa.open-in-view=false
pricewatch.scrape.interval=21600000
pricewatch.scrape.initial-delay=60000